name: Build & Publish NuGet

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack
        run: dotnet pack --output nupkgs
      - name: Publish
        run: nuget push nupkgs/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}